"""Add Expenditure model

Revision ID: 0941b0ba5765
Revises: 
Create Date: 2024-07-18 12:21:51.398647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0941b0ba5765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('date')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_contact',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('date_added')
        batch_op.drop_column('month')
        batch_op.drop_column('year')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
